all : CYK
CYK : main.cpp entropy.cpp fasta.cpp insideoutside.cpp scanner.cpp readgrammar.cpp scidouble.cpp
	g++ -o CYK main.cpp entropy.cpp fasta.cpp insideoutside.cpp scanner.cpp readgrammar.cpp scidouble.cpp
clean:
	rm CYK
